### ISSUE TITLE
Timeout problem

### ISSUE THREAD

**Issue by jackpg** [achow101/BitcointalkAccountPricer#2]
On the website it says there is a timeout error when i use my user ID. It is a full mmber account with around 500 posts!

**Comment by achow101** [comment]
What was the exact error given? Does the error happen repeatedly?

**Comment by jackpg** [comment]
I ran it five times on my laptop yesterday using the account, it was a full member account. Your site returned a timeout Error!I tried it again today, and it worked. Thankyou for your peedy assistance though!
Jack G

```
On Tuesday, 1 December 2015, 19:03, Andrew C <notifications@github.com> wrote:
```

 What was the exact error given? Does the error happen repeatedly?—

**Comment by achow101** [comment]
Since it is working, I will close this.

**Comment by jackpg** [comment]
thank you.
