### ISSUE TITLE
"Request queuing failed"

### ISSUE THREAD

**Issue by why7e** [achow101/BitcointalkAccountPricer#3]
Hey guys, I'm experimenting with your program, but whenever I open it up and try to use it, it comes up with this warning - "Request queuing failed. Please try again.".

What have I done wrong, and what can I do to stop this?

**Comment by achow101** [comment]
Are you using the site or running it yourself?

**Comment by why7e** [comment]
Running it myself.

**Comment by achow101** [comment]
Did you compile it with jsoup? How did you compile it and set everything up?

**Comment by why7e** [comment]
I just used it as is :3

**Comment by achow101** [comment]
You need to compile it for it to work. I will put up some instructions on how to compile this without using eclipse shortly.

**Comment by achow101** [comment]
There are instructions in the master branch now. Follow them and it should work

**Comment by why7e** [comment]
I'm not very knowledgable when it come to java, so when I run the "ant build" command, it says that it can't find java.exe. is that normal?

**Comment by achow101** [comment]
You need to install the JDK. I'll add that to the instructions.

**Comment by achow101** [comment]
You can follow the instructions here: https://github.com/achow101/BitcointalkAccountPricer/blob/master/INSTALL.md#running-precompiled-release to download and run the compiled output that I have started posting.
